# Generated by Django 5.1 on 2026-08-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_priority'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='backoff_base',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='job',
            name='max_backoff',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='job',
            name='max_retries',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='job',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='use_jitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'next_retry_at'], name='jobs_status_736716_idx'),
        ),
    ]
